the_entire_thesis:
	pdflatex BScPro-LDolfi.tex
	biber BScPro-LDolfi.bcf
	pdflatex BScPro-LDolfi.tex
	pdflatex BScPro-LDolfi.tex

fast:
	pdflatex BScPro-LDolfi.tex
	pdflatex BScPro-LDolfi.tex

rm_generated_files:
	rm *.bcf
	rm *.bbl
	rm *.blg
	rm *.aux
	rm *.toc
	rm *.log
	rm *blx.bib
